### ISSUE TITLE
Unicorn Invalid Instruction Error, Linux/Win10 Both

### ISSUE THREAD

**Issue by vvelitkn** [Bw3ll/sharem#55]
Tested in Ubuntu 20.04 and Win10. According to documentation, harvested DLLs from windows (corrected x64 JSON file bc json could not parse) then I tried many x32/x64 shellcodes as binary and txt, some of them killed the python session instantly, and some of them did not find the APIs but most of them gave this error.

```
	[*] Emulating x86 shellcode
	
	
Emulation error:  Invalid memory read (UC_ERR_READ_UNMAPPED)
Last address: 0x12000005
Traceback (most recent call last):
  File "/home/vvelitkn/Desktop/sharem/sharem/sharem/sharem/sharemu.py", line 1153, in test_i386
    mu.emu_start(startLoc, (CODE_ADDR + em.entryOffset) + len(code))
  File "/usr/local/lib/python3.8/dist-packages/unicorn-2.0.1.post1-py3.8-linux-x86_64.egg/unicorn/unicorn.py", line 550, in emu_start
    raise self._hook_exception
  File "/usr/local/lib/python3.8/dist-packages/unicorn-2.0.1.post1-py3.8-linux-x86_64.egg/unicorn/unicorn.py", line 392, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/unicorn-2.0.1.post1-py3.8-linux-x86_64.egg/unicorn/unicorn.py", line 663, in _hookcode_cb
    cb(self, address, size, data)
  File "/home/vvelitkn/Desktop/sharem/sharem/sharem/sharem/sharemu.py", line 697, in hook_code
    if retEnding(uc, mnemonic) or bad_instruct:
  File "/home/vvelitkn/Desktop/sharem/sharem/sharem/sharem/helper/emuHelpers.py", line 761, in retEnding
    retLoc = uc.mem_read(esp, 4)
  File "/usr/local/lib/python3.8/dist-packages/unicorn-2.0.1.post1-py3.8-linux-x86_64.egg/unicorn/unicorn.py", line 579, in mem_read
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)

	[*] CPU counter: 5
	[*] Emulation complete

	[*] No APIs discovered through emulation.

```

**Comment by Bw3ll** [comment]
Hi, 
That specific error generally means it was trying to read memory that was not mapped. For instance, trying to read from [edx], when edx points to 1 - that 1 of course would not be mapped.  There is also a timeless debugging option on the Emulation menu that you can enable that may give clues as to why something is failing - for instance, the above scenario could be seen with timeless debugging. (Timeless debugging generates a text file with all CPU instructions executed and register states before and after.) 

In the case of the above - it only got to five instructions before encountering an error with memory it could not read - that is odd.

One other thing to take into consideration is that SHAREM does **not** brute-force to try and discover the shellcode's entry point, so if the shellcode's entry point is other than 1 (or it is not known), then an error could be due to starting execution at the wrong location. Shellcode for exploitation often starts at offset 0, but with shellcode from malware, the entry point could be anywhere. It the entry point is actually something like 305, and it is encoded, and it starts at offset 0, that could be just nonsense instructions it is trying to emulate.

If you want to share one or a few sample shellcodes that generate that error message, I can take a look when I get a chance. 

It is also possible there could be installation problems. Linux is only unofficially supported - which i see comes this. There are some DLLs that need to be generated and other files moved to Linux for it to work. We do not officially support it since the DLL's are Microsoft's intellectual property - so we do not supply them directly - although it does work fine in Linux. To get it to work on Linux, you need to successfully extract and "inflate" the DLLs on a Windows machine and get some other files generated (described in Wiki) and move them to Linux. But if I can see the shellcode in question, I can see if they work on mine and maybe rule out some installation issues. If they do work on mine, then it is an installation issue. Sometimes the installation process could fail on Windows, and then emulation does not work and may give an error message if it is trying to access something from a DLL.

**Comment by Bw3ll** [comment]
Here are also some good samples you could test:
https://drive.google.com/file/d/1hq-QFqfm7CdP1FODXy_b9JwRkYHHo4F8/view?usp=sharing
Password  is **SHAREM**
They should produce APIs. If you are not getting results, then there is likely something wrong with the installation. That can help rule out a problem with installation and set up.
